"""add country to filings

Revision ID: 350be33f35b9
Revises: 8080915fbb98
Create Date: 2026-06-30 16:15:22.983953
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '350be33f35b9'
down_revision: str | None = '8080915fbb98'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=2), server_default='IT', nullable=False))
        batch_op.create_index(batch_op.f('ix_filings_country'), ['country'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filings_country'))
        batch_op.drop_column('country')

    # ### end Alembic commands ###
