"""initial schema

Revision ID: 8080915fbb98
Revises: 
Create Date: 2026-06-19 12:20:08.362723
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8080915fbb98'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issuers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('short_name', sa.String(length=256), nullable=True),
    sa.Column('lei', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lei')
    )
    with op.batch_alter_table('issuers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issuers_name'), ['name'], unique=False)

    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=True),
    sa.Column('last_name', sa.String(length=256), nullable=True),
    sa.Column('is_legal_person', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_persons_full_name'), ['full_name'], unique=True)

    op.create_table('filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.String(length=64), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('market', sa.String(length=128), nullable=True),
    sa.Column('tipologia', sa.String(length=32), nullable=True),
    sa.Column('position_status', sa.String(length=128), nullable=True),
    sa.Column('role_raw', sa.String(length=512), nullable=True),
    sa.Column('role_code', sa.String(length=16), nullable=True),
    sa.Column('notification_type', sa.String(length=32), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('parse_status', sa.String(length=16), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuers.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('filings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filings_filing_id'), ['filing_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_filings_ingested_at'), ['ingested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_filings_issuer_id'), ['issuer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_filings_parse_status'), ['parse_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_filings_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_filings_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_filings_role_code'), ['role_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_filings_source'), ['source'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('instrument_type', sa.String(length=256), nullable=True),
    sa.Column('isin', sa.String(length=32), nullable=True),
    sa.Column('nature_raw', sa.Text(), nullable=True),
    sa.Column('transaction_type', sa.String(length=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('signal_value', sa.Numeric(precision=28, scale=6), sa.Computed('price * volume', persisted=True), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('time_from', sa.Time(), nullable=True),
    sa.Column('time_to', sa.Time(), nullable=True),
    sa.Column('venue', sa.String(length=256), nullable=True),
    sa.Column('venue_mic', sa.String(length=16), nullable=True),
    sa.Column('linked_to_option_programme', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_filing_id'), ['filing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_isin'), ['isin'], unique=False)
        batch_op.create_index('ix_transactions_signal_value', ['signal_value'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_date'), ['transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index('ix_transactions_type_value', ['transaction_type', 'signal_value'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_type_value')
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_date'))
        batch_op.drop_index('ix_transactions_signal_value')
        batch_op.drop_index(batch_op.f('ix_transactions_isin'))
        batch_op.drop_index(batch_op.f('ix_transactions_filing_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('filings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filings_source'))
        batch_op.drop_index(batch_op.f('ix_filings_role_code'))
        batch_op.drop_index(batch_op.f('ix_filings_published_at'))
        batch_op.drop_index(batch_op.f('ix_filings_person_id'))
        batch_op.drop_index(batch_op.f('ix_filings_parse_status'))
        batch_op.drop_index(batch_op.f('ix_filings_issuer_id'))
        batch_op.drop_index(batch_op.f('ix_filings_ingested_at'))
        batch_op.drop_index(batch_op.f('ix_filings_filing_id'))

    op.drop_table('filings')
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_persons_full_name'))

    op.drop_table('persons')
    with op.batch_alter_table('issuers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issuers_name'))

    op.drop_table('issuers')
    # ### end Alembic commands ###
